🔧 MAINTAIN: HTML default tags
executablebooks/markdown-it-dollarmath pull request #2
Opened 2021-08-03 20:48 UTC by rowanc1

Features:
* Wrapped all content in a div/span, if this is not desired by the user we can encourage people to overwrite the rules completely
* Removed pass-through options, see https://github.com/executablebooks/markdown-it-amsmath/issues/5
  *  This is backward compatible in most cases that use katex
* Added an ID to the element when it it labelled
* Added a `labelRenderer` to `IOptions` which allows you to override the HTML of the label.

Development:
* Added json parser to rollup, couldn't get it to build without this
* Added prettier ignore file to ensure md fixture are never corrected
* Simplified the logic around the renderer using a factory

See also:
https://github.com/executablebooks/markdown-it-amsmath/issues/1
https://github.com/executablebooks/markdown-it-amsmath/issues/5

2021-08-03 21:00 UTC, rowanc1 reviewed
Some pointers in the changes below.

2021-08-03 21:00 UTC, rowanc1 commented on src/index.ts
> -  optionsBlock?: { [key: string]: any }
Removed two options here that were passed through to the render function.

2021-08-03 21:00 UTC, rowanc1 commented on src/index.ts
> +  labelRenderer?: (label: string) => string
Exposed the labelRenderer to be overridden. This will be helpful in downstream packages that want to sequentially number, etc.

2021-08-03 21:00 UTC, rowanc1 commented on tests/fixtures.spec.ts
> +        renderToString(content, { throwOnError: false, displayMode })
This is the upgrade step. Happy to get a few PRs up on relevant libs to consume this.

2021-08-03 21:00 UTC, rowanc1 commented on src/index.ts
> +}
These are the options passed on to the render function at the moment.

2021-09-10 00:01 UTC, chrisjsewell commented
Heya @rowanc1,quick one to start:

> Added json parser to rollup, couldn't get it to build without this

Could you explain what the difficulties you had with the build without it (what errors were thrown, what issue does it solve?)

2021-09-10 00:11 UTC, chrisjsewell commented on src/index.ts
> +import Renderer from "markdown-it/lib/renderer"
```suggestion
import type Renderer from "markdown-it/lib/renderer"
```

this is just for typing no?

2021-09-10 00:47 UTC, chrisjsewell requested changes
Yep just one question and nitpick, and otherwise looks good cheers

2021-11-11 22:07 UTC, rowanc1 commented
Errors here:

![image](https://user-images.githubusercontent.com/913249/141375452-90bcaaa1-e1f2-45ea-9d72-dd1301463082.png)

Seems like it should be fine to add this. I can't get anything to build without it.

Fixed up the types, should be good to go.

2021-11-12 12:34 UTC, chrisjsewell commented on rollup.config.js
> +    json()
```suggestion
    json()  // import json files as modules
```

2021-11-12 12:36 UTC, chrisjsewell approved these changes
cheers!

2021-11-12 12:42 UTC, merged

2021-11-12 15:16 UTC, rowanc1 commented
🎉 Thanks @chrisjsewell!